config/routes.rb
Invitation::Application.routes.draw do
  resources :people
  root to: "people#show"
  
  get 'contact' => "contact#index"
  get 'location' => "location#index"
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, :presence => true
  validates :ldap, :presence => true
  validates :imgId, :presence => true
  validates :position, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def index
		
	end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
	def index
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
  	@people = Person.all
  end

  def show
    @teacher = Person.where(position: 't').order('id asc')
    @assistant = Person.where(position: 'a').order('id asc')
  end

  def new
  	@person = Person.new
  end

  def create
  	@person = Person.new(person_params)

  	if @person.save
  		redirect_to people_path
  	else
  		render :new
  	end

  end

  def edit
  	@person = Person.find(params[:id])
  end

  def update
    @correct_person = Person.find(params[:id])
    @person = Person.where("ldap = ? AND id = ?", params[:person][:ldap], params[:id])

    unless @person.blank? || @person == nil
  	  if @correct_person.update(person_params)
  		  redirect_to location_path, notice: "感謝您撥冗填寫，我們已經收到您的回應。"
  	  else
  		  redirect_to :back, notice: "Sorry, wrong LDAP ID"
  	  end
    else
      redirect_to :back, notice: "Sorry, wrong LDAP ID"
    end

  end

  def destroy
  	@person = Person.find(params[:id])
  	@person.destroy
  	redirect_to people_path
  end

  private

  def person_params
	  params.require(:person).permit(:ldap, :name, :attend, :imgId, :position)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def new
		@person = Person.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_active(controller)
		params[:controller] == controller ? "active" : nil
	end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index.html.erb
<br>
<div class="row featurette">
    <div class="col-md-5">
        <%= image_tag "https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-prn2/t1.0-9/1939766_771742416188004_1581810401_n.jpg", :class => "circular_big" %>
    </div>
    <div class="col-md-6 col-md-offset-1">
    	<h2 class="featurette-heading">
          <font color="#3E97D1">沈正晧 </font>
          <span class="text-muted">資管四甲</span>
        </h2>
        <p class="lead">0978-375-615<br>s61817002@yahoo.com.tw</p>
    </div>
</div>

<br><hr><br>

<div class="row featurette"> 
    <div class="col-md-5 col-md-offset-1">
    	<h2 class="featurette-heading">
          <font color="#3E97D1">林祺翔 </font>
          <span class="text-muted">資管四甲</span>
        </h2>
        <p class="lead">0970-309-859<br>mynameisnoproblem@gmail.com</p>
    </div>
    <div class="col-md-6">
        <%= image_tag "https://scontent-b-sjc.xx.fbcdn.net/hphotos-frc3/t1.0-9/537607_379453788778127_561925494_n.jpg", :class => "circular_big" %>
    </div>
</div>

<br><hr><br>

<div class="row featurette">
    <div class="col-md-5">
        <%= image_tag "https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-ash3/t1.0-9/992996_680648581950757_223908945_n.jpg", :class => "circular_big" %>
    </div>
    <div class="col-md-6 col-md-offset-1">
        <h2 class="featurette-heading">
          <font color="#3E97D1">王大雄 </font>
          <span class="text-muted">資管四乙</span>
        </h2>
        <p class="lead">0935-881-717<br>beardada0916@gmail.com</p>
    </div>
</div>

<br><hr><br>

<div class="row featurette"> 
    <div class="col-md-5 col-md-offset-1">
        <h2 class="featurette-heading">
          <font color="#3E97D1">曾宇澤 </font>
          <span class="text-muted">資管四乙</span>
        </h2>
        <p class="lead">0975-831-568<br>prankcatax@gmail.com</p>
    </div>
    <div class="col-md-6">
        <%= image_tag "https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-ash3/t1.0-9/1385158_762153567134802_769922508_n.jpg", :class => "circular_big" %>
    </div>
</div>

<br>   

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_top_bar.html.erb
<main role="main">
  <div class="container">
    <div class="header">
      <ul class="nav nav-pills pull-right">
        <li class="<%= is_active('people') %>"><%= link_to("Home", root_path) %></li>
        <li class="<%= is_active('location') %>"><%= link_to("Location", location_path) %></li>
        <li class="<%= is_active('contact') %>"><%= link_to("Contact", contact_path) %></li>
      </ul>
      <h3 class="text-muted">第三十屆輔仁資管謝師宴邀請函</h3>
    </div>

    <%= yield %>
    
    <div class="footer">
      <p>&copy; FJU Information Management 2014.</p>
      <p>Created and Designed by Tony & Alven.</p><br>
    </div>

  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "第三十屆輔仁資管謝師宴邀請函" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Invitation" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/top_bar'%>
  </body>
</html>

app/views/location/index.html.erb
<br>
<div class="row featurette">
  <div class="col-md-5">
  	<%= image_tag "map.png" %>
  </div>
  <div class="col-md-7">
    <h2 class="featurette-heading">台北花園大酒店</h2>
    <p class="lead">
      <%= link_to("台北市中正區中華路二段1號", "https://www.google.com.tw/maps/place/台北市中正區中華路二段1號", target: "_blank") %>
      <br>(02) 2314-6611
    </p>
  </div>
</div>

<br><br>
<div>
  <%= image_tag "map3.jpg" %>
</div>
<br><br>

<div class="row featurette">
  <div class="col-md-12">
  	<h2 class="featurette-heading">交通資訊</h2>
  </div>
  <div class="col-md-6">    
    <p class="lead">
      <span class="text-muted">捷運</span><br>
      <span>小南門線<font color="#3E97D1">小南門站2號出口</font></span><br>
      <span>步行約3分鐘，至中華路愛國西路口即可到達。</span>
      <br><br>
      <span>板南線<font color="#3E97D1">西門捷運站2號出口</font></span><br>
      <span>步行約5分鐘，至中華路愛國西路口即可到達。</span>
    </p>
    <div class="col-md-12">
  	  <%= image_tag "map2.png" %>
  	</div>
  </div>

  <div class="col-md-6">
  	<p class="lead">
	  <span class="text-muted">公車</span><br>
	  <span>搭乘12、202、212、212(直行車)、223、250、260、307、、667、670、671、673、812、246、249、604、246、253、205、242於「<font color="#3E97D1">聯合醫院和平院區站</font>」下車步行約1分鐘即可抵達。</span>
	  <br><br>
	  <span>搭乘9、218、231、234、263、265、302、310、628、651、656、657、658、601、701、702、703、705於「<font color="#3E97D1">小南門站</font>」下車步行約3分鐘。</span>
	  <br><br>
	  <span>搭乘38、206、252、262、270、304承德線、304重慶線、604、660於「<font color="#3E97D1">小南門和平院區站</font>」下車步行約2分鐘至中華路與愛國西路口即可到達。</span><br>
   </p>
  </div>
</div>
<br>

app/views/people/edit.html.erb
<div class="row featurette">
  <div class="col-md-6">
    <div class="form-group">
      <%= simple_form_for @person do |f| %>
        <%= @person.position == "t" ? @person.name + " 老師" : @person.name + " 助教/秘書" %>
        <br><br>
        <%= f.input :attend, as: :radio_buttons, label: "是否出席？" %><br>
        <%= f.input :ldap, label: "請輸入您的LDAP帳號以供我們驗證", :input_html => {value: ""} %><br>
        <%= f.submit "提交", :class => "btn btn-primary"  %>          
      <% end %>
    </div>
  </div>

  <div class="col-md-3 col-md-offset-3">
    <%= image_tag "browser.png"%>
  </div>
</div><br>

app/views/people/index.html.erb
<% count = 0 %>
<div>
  <%= link_to("Initial", new_person_path, :class => "btn btn-mini")%>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Position</th>
        <th>attend?</th>
        </tr>
    </thead>
    <tbody>
      <% @people.each do |p| %>
      <tr>
        <td><%= p.id %></td>
        <!-- <td><%= p.imgId %></td>
        <td><%= p.ldap %></td> -->
        <td><%= p.name %></td>
        <td><%= p.position=="t" ? "老師" : "助教/秘書" %></td>
        <td><%= p.attend.to_s %></td>
        <!-- <td> 
          <%= link_to("Delete", person_path(p), :class => "btn btn-mini", :method => :delete, :confirm => "Are you sure?" )%>
        </td> -->
      </tr>
        <% if p.attend == true %>
          <% count += 1 %>
        <% end %><!-- if -->  
      <% end %><!-- each --> 
      <tr>
        <td>出席總人數</td>
        <td>--</td> 
        <td>--</td> 
        <td><%= count %>人</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/people/new.html.erb
<%= simple_form_for @person do |f| %>
  <%= f.input :ldap, label: "LDAP", placeholder: "LDAP", :input_html => {:class =>"form-control"} %><br>
  <%= f.input :name, label: "姓名", placeholder: "name", :input_html => {:class =>"form-control"} %><br>
  <%= f.input :imgId, label: "Image ID", placeholder: "Image ID", :input_html => {:class =>"form-control"} %><br>
  <%= f.input :position, label: "職位(老師=t, 助教=a)", placeholder: "position", :input_html => {:class =>"form-control"} %>
  <div class="form-group"><br>
  	<%= f.input :attend, as: :radio_buttons, label: "是否出席？" %>
  </div>
  <br>
  <div class="form-actions">
	<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
  </div>
  <br>
<% end %>

app/views/people/show.html.erb
<% teacherLink = "http://www.im.fju.edu.tw/Chweb/Teacher/LoadImg.asp?TeaID=" %>
<% assistantLink = "http://www.im.fju.edu.tw/Chweb/Teacher/LoadImgAss.asp?ID=" %>

<div class="jumbotron">
  <h2>親愛的師長們：</h2><br>
  <p class="lead">
    學生們為了感謝您的辛勞，謹訂於 103年6月18日（三）<br>晚間19:00，假臺北花園大酒店—六國餐廳舉辦「第三十屆輔仁資管謝師宴」，敬請撥冗參加！
    <br>
  </p>
  <p class="lead">
    請師長們在下方列表中選取您的大名，以幫助我們完成出席調查表，若師長們有任何的問題皆可向系秘書或是相關負責人詢問，恭呈此函給您，敬邀備宴。
  </p> 
</div>

<div class="row featurette">
  <div class="col-md-12 table-responsive">
    <div class="table-responsive">
      <h3 class="text-muted">老師</h3>
  	  <table class="table table-striped">
  	  	<tbody>
          <% count = 1 %>
          <% @teacher.each do |teacher| %>
            <% if count>4 && count%4 == 1%>
              <tr>
            <% end %><!-- if -->

            <td width="90px">
              <%= link_to(image_tag(teacherLink+teacher.imgId, :class => "circular", alt: ""), edit_person_path(teacher))%>
            </td>
            <td>
              <%= link_to(teacher.name, edit_person_path(teacher))%><br>
              <% if teacher.attend %>
                <font class="list-group-item-success">出席</font>
              <% elsif teacher.attend == nil %>
                <font class="list-group-item-warning">尚未填寫</font>
              <% else %>
                <font class="list-group-item-danger">不出席</font>
              <% end %>
            </td>
            <% count += 1 %>
          <% end %><!-- each -->
              </tr>   
  		  </tbody>
    	</table>
      
      <br>

      <h3 class="text-muted">助教 秘書</h3>
      <table class="table table-striped">
        <tbody>
          <% count = 1 %>
          <% @assistant.each do |assistant| %>
            <% if count>4 && count%4 == 1%>
              <tr>
            <% end %><!-- if -->

            <td width="90px">
              <%= link_to(image_tag(assistantLink+assistant.imgId, :class => "circular"), edit_person_path(assistant))%>
            </td>
            <td>
              <%= link_to(assistant.name, edit_person_path(assistant))%><br>
              <% if assistant.attend %>
                <font class="list-group-item-success">出席</font>
              <% elsif assistant.attend == nil %>
                <font class="list-group-item-warning">尚未填寫</font>
              <% else %>
                <font class="list-group-item-danger">不出席</font>
              <% end %>
            </td>
            <% count += 1 %>
          <% end %><!-- each -->
              </tr>   
        </tbody>
      </table>
	  </div>
    <br><font class="text-muted">註：以上排序係依照教師職稱及到校年月排序</font>
  </div>
</div><br>

app/views/welcome/new.html.erb
<div class="jumbotron">
  <h1>Jumbotron heading</h1>
  <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
</div>

<div class="row featurette">
  <div class="col-md-6">
    <div class="form-group">
      <%= simple_form_for @person do |f| %>
        <%= f.input :name, label: "姓名", placeholder: "name", :input_html => {:class =>"form-control"} %>
    </div>
  </div>
  <div class="col-md-6 col-md-offset-6"></div>

  <div class="col-md-5">
    <div class="form-group">
        <%= f.input :attend, as: :radio_buttons, label: "是否出席？" %>
    </div>
    <div class="form-group">
        <%= f.button :submit, "提交", :class => "btn btn-primary"  %>
      <% end %>
    </div>
  </div>

  <div class="col-md-3 col-md-offset-4">
    <%= image_tag "graph.png"%>
  </div>
</div>